### ISSUE TITLE
Add collaborators to this repo

### ISSUE THREAD

**Issue by riezebosch** [riezebosch/programmingmf#1]
## Comment below to be added as a collaborator

We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API. Once you comment, we will add you as a collaborator.

You'll start to receive a lot of emails. (❗) You can slow these down immediately by clicking the **Unwatch** button at the top of the page and selecting either the **Participating and @mentions** or **Ignore** option.

**Comment by suard** [comment]
hallo?

**Comment by ninodejong** [comment]
Hello?

**Comment by peterfennema** [comment]
hoi

**Comment by skirsimae** [comment]
Hi

**Comment by Staartvin** [comment]
_Alles kits achter de rits?_

**Comment by ninodejong** [comment]
![image](https://github.com/riezebosch/programmingmf/assets/9357464/d299cfcf-46d9-4060-83c7-095f18a53f5c)

**Comment by Staartvin** [comment]
Bye bye! 👋🏻

**Comment by timfennis** [comment]
Hoi!
